#!/usr/bin/env zsh

# based on https://useyourloaf.com/blog/format-swift-with-a-git-commit-hook/

# Staged (cached) added/copied/modified/renamed files
IFS=$'\n' files=($(git diff --cached --name-only --diff-filter=ACMR | grep '\.swift$'))
if (( ${#files[@]} != 0 )); then
  swift format --in-place --parallel "$files[@]"
  git add "$files[@]"
fi
